---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-worker
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
        - /spec/source/targetRevision
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "observability.{{.nameNormalized}}"
    spec:
      destination:
        namespace: monitoring
        name: "{{.name}}"
      project: default
      source:
        path: manifests/observability-worker/k8s
        # repoURL: https://github.com/kuadrant/deployment
        # targetRevision: HEAD
        repoURL: https://github.com/david-martin/deployment
        targetRevision: observability
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ServerSideApply=true
