apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Install prometheus stack
- github.com/prometheus-operator/kube-prometheus?ref=release-0.13 
# Install gateway-api-state-metrics configuration
- github.com/Kuadrant/gateway-api-state-metrics/config/kuadrant?ref=0.5.0
# Configure scraping of kuadrant operators
- ./operators.yaml
# Configure scraping of istio metrics
- ./istio

# Scale down alertmanager to save on resources
patches:
- patch: |-
    kind: Alertmanager
    metadata:
      name: main
    spec:
      replicas: 1
  target:
    kind: Alertmanager
    name: main
# Give prometheus permissions to get metrics and read services, endpoints & pods
- path: rbac/cluster_role.yaml
# Mount custom-resource-state config into kube-state-metrics pod to configure scraping gateway state metrics
- path: ksm_deployment_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: kube-state-metrics
    version: v1
# Allow kube-state-metrics to read gateway & kuadrant resources
- path: rbac/ksm_clusterrole_patch.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kube-state-metrics
    version: v1
# Remove grafana from workers
- target:
    labelSelector: "app.kubernetes.io/component=grafana"
  patch: |
    $patch: delete
    kind: Kustomization
    metadata:
      name: whatever
