apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: thanos-ruler
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/version: v0.29.0
  name: thanos-ruler
  namespace: monitoring
