apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-ruler
    app.kubernetes.io/instance: thanos-ruler
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/version: v0.29.0
  name: thanos-ruler
  namespace: monitoring
spec:
  ports:
    - name: web
      protocol: TCP
      port: 10902
      targetPort: web
    - name: grpc
      protocol: TCP
      port: 10901
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: thanos-ruler
    app.kubernetes.io/name: thanos-ruler
    app.kubernetes.io/version: v0.29.0